Round pixel values of `intrinsicSize` with `YGRoundPixelValue`
facebook/yoga pull request #1213
Opened 2023-01-15 03:53 UTC by stleamist

This PR makes `intrinsicSize` return rounded pixel values using `YGRoundPixelValue` as `YGApplyLayoutToViewHierarchy` does.

This change prevents text truncation due to the low precision of C++ `float` when sizing the view containing `UILabel` using `intinsicSize`.

```swift
override func sizeToFit() {
  self.bounds.size = self.yoga.intrinsicSize
}
```

2023-01-16 04:54 UTC, NickGerleman commented
Change makes sense to me.

For record-keeping, could you add a before/after screenshot to the PR description?

For awareness, the automated tests for YogaKit, and build on latest toolchain have been broken for a while, so we will have reduced coverage for this change against any existing automated tests. It's been on the infrastructure todo list, but after fixing the CMake build/test experience, and UTs for JNI bindings/Android build. There are a lot of PRs fixing various bits of the build, but I haven't had the experience with the Apple build to understand the whole of what we should be doing to the existing build logic, vs if we should just axe it, follow the Cocoapods/SPM guide for building a new package + example, then follow the leads where it needs code-changes.

2023-01-21 02:13 UTC, rozele commented
Perhaps I'm missing something here, but as I understand, Yoga already returns values rounded to the pixel grid assuming you set the scale via YGConfigSetPointScaleFactor. Why do you need to round a value that should presumably already be rounded?

2023-01-24 22:19 UTC, NickGerleman requested changes
See comments from Eric, and request for test plan

2023-02-08 04:39 UTC, NickGerleman commented
> Perhaps I'm missing something here, but as I understand, Yoga already returns values rounded to the pixel grid assuming you set the scale via YGConfigSetPointScaleFactor. Why do you need to round a value that should presumably already be rounded?

Just to check, is the idea here that:
1. Yoga already does its own rounding (`YGRoundToPixelGrid()`)  based on `pointScaleFactor`, when laying out a node.
2. The YogaKit-specific `YGRoundPixelValue()` and its usage should be removed, and we should rely on Yoga to do all of the rounding itself

I am seeing that YogaKit is already calling `YGConfigSetPointScaleFactor()` (though assuming the density never changes, which is... probably fine on iOS). So this would end up looking like just removing the existing usage I think.

2023-06-15 20:30 UTC, NickGerleman commented
We are deprecating YogaKit as part of the Yoga 2.0 release. We are still going to release a new revision based on the current state of the repo, but won't be accepting new contributions, since we are going to be removing it from the repo after.

2023-06-15 20:30 UTC, closed without merging