Add compiler option to call measure callback on all nodes
facebook/yoga pull request #995
Opened 2020-04-06 19:02 UTC by sagokhal

When using Yoga in combination with external layout systems (brown field scenarios) Yoga leaf nodes can be subtrees w.r.t. the external layout system.
During the measure phase, these subtrees need to be measured by the external layout system - even if the Yoga node's mode is YGMeasureModeExactly.
This change adds a preprocessor conditional that can be set by out-of-tree platforms to always call measure for all nodes that have the measure callback.

2020-04-08 10:54 UTC, SidharthGuglani commented on yoga/Yoga.cpp
>    if (widthMeasureMode == YGMeasureModeExactly &&
This is still getting executed even if measure callback is called on all the nodes. 
I think you want to use measuredSize after measure callback

2020-04-08 10:55 UTC, SidharthGuglani commented on yoga/Yoga.cpp
> +#ifdef YOGA_CALL_MEASURE_CALLBACK_ON_ALL_NODES
Instead of compiler option, it will be better to pass a flag via YGConfig

2020-05-11 17:15 UTC, NickGerleman commented
@SidharthGuglani sorry for the delay here. Are there any remaining issues?

2020-05-28 23:21 UTC, sagokhal commented
Hey @SidharthGuglani, just wanted to follow-up on this. Are they any more changes you recommend to get this in?

2020-05-30 11:02 UTC, woehrl01 commented
Hi all, I just stumbled over it based on https://github.com/microsoft/react-native-windows/issues/3994. I would add two additional suggestions. 
1. Instead of adding a new parameter for the `YGConfigRef` you can use `node->getConfig()` from the passed `node`. 
2. Instead of adding a new `bool` field and having to extend the API (would should be als added at best all implemented languages) + breaking the ABI, you can add an extend the `YGExperimentalFeature*` enum in `YGEnum.h` and use the existing `YGConfigSetExperimentalFeatureEnabled`. At least we added that feature a few years ago exactly for such things.

2020-06-05 18:36 UTC, sagokhal commented
@woehrl01 Both those points makes sense. I'll make those changes.

2020-06-05 21:28 UTC, woehrl01 commented on yoga/Yoga.cpp
> -    // Measure the text under the current constraints.
I think the removing of that comment was unintentional and should be reverted.

2022-10-03 23:43 UTC, NickGerleman commented
@acoates-ms @rozele @sagokhal do any of you have thoughts on the desired outcome of this PR?

2022-10-05 01:33 UTC, rozele commented
When last discussed with @acoates-ms, we agreed that this should not be the default behavior for react-native-windows, but it sounds like it's still needed for react-native-win32, so having an experimental flag and a corresponding QuirkSetting in react-native-windows is probably a good idea.

2022-12-29 18:41 UTC, NickGerleman requested changes
A couple feedback items to merge:
1. YGEnums is generated code. We should edit `enums.py` and regenerate the other language bindings.
2. Could we rename `YGExperimentalFeatureCallMeasureCallbackOnAllNodes` to `YGExperimentalFeatureMeasureCallbackOnMeasureModeExactly`?

2023-01-13 23:18 UTC, closed without merging